### ISSUE TITLE
Novo nome para a equipe?

### ISSUE THREAD

**Issue by zaqmarlon** [IFRN-SC/Wall-E-2018-#1]
![walle](https://user-images.githubusercontent.com/31693006/37257209-c709b7a6-2544-11e8-90ec-75a6755612a9.jpg)

**Comment by lennedy** [comment]
Como assim?? Qual o problema com wall-e??

**Comment by zaqmarlon** [comment]
There's many Wall-Es...

**Comment by lennedy** [comment]
E qual nomes vc sugere?
Eu proponho solares, alvorada. Nome de dois planetas dos livros de asimov.
Também tem o nome Giskard que é o nome de um dos robôs de um livro de asimov.
O que vc acha?
O que vcs conseguem propor mais?

**Comment by zaqmarlon** [comment]
Redutor, talvez...

**Comment by lennedy** [comment]
Um nome muito legal também do filme Wall-e é um outro robô chamado: 

> burn-e.

![kl7knclk7po6gk1njumfj0epol5](https://user-images.githubusercontent.com/4775968/39411767-11ab8bea-4be7-11e8-9589-89d8c8ada328.jpg)

**Comment by zaqmarlon** [comment]
Vamos mudar o nome antes do amistosoooo

**Comment by PauloVLB** [comment]
Sugestão de Abmael: PYIA ou VYIA

**Comment by zaqmarlon** [comment]
Q?
