### ISSUE TITLE
Identificação do Cinza/Sala 3

### ISSUE THREAD

**Issue by lennedy** [IFRN-SC/Wall-E-2018-#12]
Chegando ao final da rampa o robô deve identificar o cinza e baseado nessa identifiação o robô deve iniciar a sala3.

**Comment by lennedy** [comment]
Go go go!
:smile:

**Comment by zaqmarlon** [comment]
Teste para identificar o cinza/inicio sala3 - Estrategia.cpp #16

**Comment by PauloVLB** [comment]
@lennedy , fiz como @isaacmarlon sugeriu. Depois de estar na rampa, trato o próximo "preto_preto_preto_preto" como cinza. Pelos os meus testes está dando certo.

**Comment by isaacmarlon** [comment]
@PauloVLB, muito provavelmente essa condição funcionará. Maaaas... vamos desenvolver outra estratégia para essa identificação - tudo pode acontecer.

**Comment by zaqmarlon** [comment]
Trataremos o cinza como preto.
