### ISSUE TITLE
Diagrama das classes

### ISSUE THREAD

**Issue by zaqmarlon** [IFRN-SC/Wall-E-2018-#15]
Criar um diagrama para demonstrar visualmente a relação entre as classes.

**Comment by lennedy** [comment]
massa!

**Comment by zaqmarlon** [comment]
- [x] Cod.ino 
- [x] Estrategia.h
- [x] Botao.h
- [x] SensoresWallE.h 
- [ ] Calibracao2.h
- [ ] Refletancia.h
- [ ] SensorDeCor.h
- [ ] Matematica.h
