### ISSUE TITLE
Fazer cadastro Currículo Lattes

### ISSUE THREAD

**Issue by lucileidedantas** [IFRN-SC/Wall-E-2018-#20]
Fazer o currículo na plataforma Lattes.

Segue o link: http://lattes.cnpq.br/ (Abrir menu: Cadastrar novo currículo - Menu lateral à direita).

Precisamos que vocês se cadastrem nessa plataforma para poder cadastrar vocês em projetos no SUAP e até em alguns eventos.

- [x] Isaac
- [x] Yasmim
- [x] Paulinho
- [ ] Rosimário
- [ ] Abmael

**Comment by isaacmarlon** [comment]
- [ ] Isaac
- [ ] Yasmim
- [ ] Paulinho
- [ ] Rosimário
- [ ] Abmael
