### ISSUE TITLE
Testar nova classe "Garra"

### ISSUE THREAD

**Issue by zaqmarlon** [IFRN-SC/Wall-E-2018-#21]
Identificar erros e aprimorar o código

- [x] Ajustes: constantes ANG_INIT e DELAY..

**Comment by isaacmarlon** [comment]
- [ ] Ajustes: constantes ANG_INIT e DELAY.

**Comment by zaqmarlon** [comment]
@PauloVLB , acho que podemos fechar essa issue, não é?
