### ISSUE TITLE
Identificar e se alinhar a bola

### ISSUE THREAD

**Issue by lennedy** [IFRN-SC/Wall-E-2018-#4]
Essa tarefa faz parte da realização da sala3. Utilizando o sensor sonar ou uma câmera será necessário identificar a posição da vítima, alinhar-se e se aproximar da mesma

**Comment by zaqmarlon** [comment]
Acho que seria interessante desenvolvermos à priori um "código primário" para a identificação com os sonares. Logo após, desenvolveríamos o "código secundário" para a identificação simultânea sonar/câmera. 

@lennedy , @PauloVLB

**Comment by zaqmarlon** [comment]
Já conseguimos localizar usando o sonares, confere? @PauloVLB

**Comment by zaqmarlon** [comment]
Testar a procura da bola em duas etapas... Se não encontrar, voltar e se alinhar na parede.

Prioridade:
- [ ] Fazer "movimentação sentinela" (lados);

Final:
- [ ] Voltar o robô (acumulador de delay's);
- [ ] Fazer com que o robô se alinhe com a parede e procure novamente;
